#!/bin/sh

DIFFDIR="/tmp"
CURRENTDIR="/var/tmp/oldsystems"

sudo mkdir -p $CURRENTDIR
sudo mkdir -p $DIFFDIR

# Setup current packages and diffs with desired packages
OLDFILE="$CURRENTDIR/old-system-$(ls -1 $CURRENTDIR | wc -l | awk '{print $1}')"
sudo pkg prime-list > "$OLDFILE"
sudo sort /home/main/declarativebsd/system.dcl > "$CURRENTDIR/current-system"

DIFF_COMMAND="diff --ignore-all-space --ignore-blank-lines '$CURRENTDIR/current-system' $OLDFILE"
DIFF_ADD=$(echo $DIFF_COMMAND | sh | grep -v "#" | grep "<" |  awk '{print $2}')
DIFF_RM=$(echo $DIFF_COMMAND | sh | grep -v "#" | grep ">" |  awk '{print $2}')
LONG_ASS_LINE="-----------------------------------------------------"

# Ugly printfs to get funny colors
if [ "$DIFF_ADD" != '' ]; then
printf "\033[32m $LONG_ASS_LINE-Adding-$LONG_ASS_LINE\n  $(echo $DIFF_ADD)\033[97m\n\n"
fi

if [ "$DIFF_RM" != '' ]; then
printf "\033[31m $LONG_ASS_LINE-Removing-$LONG_ASS_LINE\n  $(echo $DIFF_RM)\033[97m\n\n"
fi


read -r -p "Are you sure? (Y/n) : " REPLY
echo
if [ "$REPLY" != 'n' ];
then
  # Add the new system, then remove the old one
  echo $DIFF_ADD | sudo xargs pkg install -y
  echo $DIFF_RM | sudo xargs pkg remove -y
  sudo pkg autoremove -y
fi
